In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
import numpy as np
import matplotlib.pyplot as plt

# Concatenate Vs Stack
Concatenating joins a sequence of tensors along an existing axis, and stacking joins a sequence of tensors along a
new axis.

    Join Method	    Where

    · Concatenate	Along an existing axis
    · Stack	        Along a new axis

# How To Add Or Insert An Axis Into A Tensor

In [2]:
t1 = torch.tensor([1, 1, 1]) # rank=1 tensor (1d)
print(t1.shape)
print(t1.unsqueeze(dim=0))
print(t1.unsqueeze(dim=1))

torch.Size([3])
tensor([[1, 1, 1]])
tensor([[1],
        [1],
        [1]])


    · Unsqueeze by dim=0 (1D tensor!) -> 2D tensor with a SINGLE row (axis=0)
    · Unsqueeze by dim=1 (1D tensor!) -> 2D tensor with number of rows, corresponding to the previous number of columns
    (put value from each column to separate row)

# Stack Vs Cat In PyTorch

In [3]:
t1 = torch.tensor([1, 1, 1])
t2 = torch.tensor([2, 2, 2])
t3 = torch.tensor([3, 3, 3])

Concatenation happens along EXISTING axis.

In [11]:
print(
    torch.cat(
        tensors=(t1, t2, t3),
        dim=0
    )
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])


Stacking happens along NEW axis.

In [12]:
print(
    torch.stack(
        tensors=(t1, t2, t3),
        dim=0
    )
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


In [13]:
print(
    torch.stack(
        tensors=(t1, t2, t3),
        dim=1
    )
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


Stacking is basically concatenating along the added axes (unsqueeze the tensors)

In [14]:
print(
    torch.cat(
        tensors=(
            t1.unsqueeze(dim=0),
            t2.unsqueeze(dim=0),
            t3.unsqueeze(dim=0)
        ),
        dim=0
    )
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


In [15]:
print(
    torch.cat(
        tensors=(
            t1.unsqueeze(dim=1),
            t2.unsqueeze(dim=1),
            t3.unsqueeze(dim=1)
        ),
        dim=1
    )
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


# Stack Vs Concat In TensorFlow

In [16]:
import tensorflow as tf

In [17]:
t1 = tf.constant([1, 1, 1])
t2 = tf.constant([2, 2, 2])
t3 = tf.constant([3, 3, 3])

In [21]:
print(
    tf.concat(
        values=(t1, t2, t3),
        axis=0
    )
)

tf.Tensor([1 1 1 2 2 2 3 3 3], shape=(9,), dtype=int32)


In [20]:
print(
    tf.stack(
        values=(t1, t2, t3),
        axis=0
    )
)

tf.Tensor(
[[1 1 1]
 [2 2 2]
 [3 3 3]], shape=(3, 3), dtype=int32)


In [22]:
print(
    tf.stack(
        values=(t1, t2, t3),
        axis=1
    )
)

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


Again, the results are the same as the PyTorch results. Now, we'll concatenate these after manually inserting the new
dimension.

In [23]:
print(
    tf.concat(
        values=(
            tf.expand_dims(input=t1, axis=0),
            tf.expand_dims(input=t2, axis=0),
            tf.expand_dims(input=t3, axis=0)
        ),
        axis=0
    )
)

tf.Tensor(
[[1 1 1]
 [2 2 2]
 [3 3 3]], shape=(3, 3), dtype=int32)


In [24]:
print(
    tf.concat(
        values=(
            tf.expand_dims(input=t1, axis=1),
            tf.expand_dims(input=t2, axis=1),
            tf.expand_dims(input=t3, axis=1)
        ),
        axis=1
    )
)

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


# Stack Vs Concatenate In NumPy

In [25]:
t1 = np.array([1, 1, 1])
t2 = np.array([2, 2, 2])
t3 = np.array([3, 3, 3])

In [31]:
print(
    np.concatenate(
        (t1, t2, t3),
        axis=0,
    )
)

[1 1 1 2 2 2 3 3 3]


In [34]:
print(
    np.hstack(
        (t1, t2, t3)
    )
)

[1 1 1 2 2 2 3 3 3]


In [33]:
print(
    np.vstack(
        (t1, t2, t3)
    )
)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [35]:
print(
    np.stack(
        (t1, t2, t3),
        axis=1
    )
)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [37]:
print(
    np.concatenate(
        (np.expand_dims(t1, axis=0),
         np.expand_dims(t2, axis=0),
         np.expand_dims(t3, axis=0)
         ),
        axis=0
    )
)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [38]:
print(
    np.concatenate(
        (np.expand_dims(t1, axis=1),
         np.expand_dims(t2, axis=1),
         np.expand_dims(t3, axis=1)
         ),
        axis=1
    )
)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
print(
    np.column_stack((t1, t2, t3)) == np.stack((t1, t2, t3), 1)
)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [47]:
print(
    np.row_stack((t1, t2, t3) == np.stack((t1, t2, t3), axis=0))
)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Stack Or Concat: Real-Life Examples

    1.  Joining Images Into A Single Batch
    2.  Joining Batches Into A Single Batch
    3.  Joining Images With An Existing Batch

# Joining Images Into A Single Batch
uppose we have three individual images as tensors. Each image tensor has three dimensions, a channel axis, a height
axis, a width axis. Note that each of these tensors are separate from one another. Now, assume that our task is to join
these tensors together to form a single batch tensor of three images.

    · Remember that Image is of shape (color_channels, height, width) !

In [63]:
t1 = torch.zeros(3, 28, 28) # single image containing 3 color channels being 28x28px large
t2 = torch.zeros(3, 28, 28)
t3 = torch.zeros(3, 28, 28)

In [64]:
single_batch = torch.stack(
    tensors=(t1, t2, t3),
    dim=0
)

In [65]:
print(single_batch.shape)

torch.Size([3, 3, 28, 28])


# Joining Batches Into A Single Batch
Well, notice how there is an existing dimension that we can concat on (in every batch we have a dimension for number of
images). This means that we concat these along the batch (number of images) dimension.

In this case there is no need to stack.

In [66]:
t1 = torch.zeros(5, 3, 28, 28) # single batch containing single imag, 3 color channels, 28x28px
t2 = torch.zeros(5, 3, 28, 28)
t3 = torch.zeros(5, 3, 28, 28)

In [67]:
single_batch = torch.cat(
    tensors=(t1, t2, t3),
    dim=0
)

In [68]:
print(single_batch.shape)

torch.Size([15, 3, 28, 28])


# Joining Images With An Existing Batch
Do we concat or do we stack?

Well, notice how the batch axis already exists inside the batch tensor. However, for the images, there is no batch axis
in existence. This means neither of these will work. To join with stack or cat, we need the tensors to have matching
shapes.

So then, are we stuck? Is this impossible?

It is indeed possible. It’s actually a very common task. The answer is to first stack and then to concat.

In [69]:
single_batch = torch.zeros(10, 3, 28, 28)
t1 = torch.zeros(3, 28, 28)
t2 = torch.zeros(3, 28, 28)
t3 = torch.zeros(3, 28, 28)

Firstly to create a batch of images (rank 3 tensors) we need to stack these images vertically (dim=0) to create that
batch size dimension

In [ ]:
single_batch2 = torch.stack(
    tensors=(t1, t2, t3),
    dim=0
)

Because we have now 2 batches, we can easily concatenate them, because they both contain the batch size dimension.

In [ ]:
new_batch = torch.cat(
    tensors=(single_batch, single_batch2),
    dim=0
)

In [72]:
print(new_batch.shape)

torch.Size([13, 3, 28, 28])
